" --- Disable legacy stuff
set nocompatible
set backspace=indent,eol,start


" --- Activate filetype specific stuff
filetype plugin on
filetype indent on
set autoread


" --- Menu settings
set path+=**

set wildmenu
set wildignore=*.o,*~,*.pyc,*.class


" --- Display settings
syntax on
set showmatch
set ruler
set number

if has("gui_running")
	set guioptions-=T
	set guioptions+=e
endif


" --- Search options
set ignorecase
set smartcase
set incsearch


" --- Set vim files directories
set undodir=$XDG_CACHE_HOME/vim,/tmp
set directory=$XDG_CACHE_HOME/vim,/tmp
set backupdir=$XDG_CACHE_HOME/vim,/tmp
set viewdir=$XDG_CACHE_HOME/vim,/tmp
set viminfo+=n$XDG_CACHE_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$VIM,$VIMRUNTIME
let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc"


" --- Tweaks for file browsing
let g:netrw_banner=0        " disable annoying banner
let g:netrw_browse_split=4  " open in prior window
let g:netrw_altv=1          " open splits to the right
let g:netrw_liststyle=3     " tree view
let g:netrw_list_hide=netrw_gitignore#Hide()
let g:netrw_list_hide.=',\(^\|\s\s\)\zs\.\S\+'


